### ISSUE TITLE
Support MetaMask privacy mode

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/xcontract#6]
Snippet in middle of https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**Comment by James-Sangalli** [comment]
1297243a39be71def523c053bb351e626da379d6 

API is unstable however, when it is working I will merge it and deploy

**Comment by James-Sangalli** [comment]
d82c932c3c8e2c45f2a79b7332b72fbbae7b7ee3 had lost my commit somewhere that caught if it was undefined.
